/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/auth/login": {
    post: {
      parameters: {
        body: {
          /** Login payload */
          body: definitions["authrequest.Login"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["response.Envelope"] & {
            data?: definitions["authresponse.Session"];
          };
        };
        /** Bad Request */
        400: {
          schema: definitions["response.Envelope"];
        };
        /** Unauthorized */
        401: {
          schema: definitions["response.Envelope"];
        };
      };
    };
  };
  "/auth/logout": {
    post: {
      parameters: {
        body: {
          /** Refresh token */
          body: definitions["authrequest.Refresh"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["response.Envelope"];
        };
        /** Bad Request */
        400: {
          schema: definitions["response.Envelope"];
        };
      };
    };
  };
  "/auth/refresh": {
    post: {
      parameters: {
        body: {
          /** Refresh payload */
          body: definitions["authrequest.Refresh"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["response.Envelope"] & {
            data?: definitions["authresponse.Session"];
          };
        };
        /** Unauthorized */
        401: {
          schema: definitions["response.Envelope"];
        };
      };
    };
  };
  "/auth/register": {
    post: {
      parameters: {
        body: {
          /** Registration payload */
          body: definitions["authrequest.Register"];
        };
      };
      responses: {
        /** Created */
        201: {
          schema: definitions["response.Envelope"] & {
            data?: definitions["authresponse.Session"];
          };
        };
        /** Bad Request */
        400: {
          schema: definitions["response.Envelope"];
        };
        /** Conflict */
        409: {
          schema: definitions["response.Envelope"];
        };
      };
    };
  };
  "/exchange-rates": {
    get: {
      responses: {
        /** OK */
        200: {
          schema: definitions["response.Envelope"] & {
            data?: definitions["fxresponse.Rate"][];
          };
        };
        /** Unauthorized */
        401: {
          schema: definitions["response.Envelope"];
        };
      };
    };
  };
  "/invitations/me": {
    get: {
      responses: {
        /** OK */
        200: {
          schema: definitions["response.Envelope"];
        };
      };
    };
  };
  "/invitations/{token}/accept": {
    post: {
      responses: {
        /** OK */
        200: {
          schema: definitions["response.Envelope"] & {
            data?: definitions["participantresponse.Participant"];
          };
        };
        /** Not Found */
        404: {
          schema: definitions["response.Envelope"];
        };
      };
    };
  };
  "/ping": {
    /** Returns a fully populated envelope proving the API composition root is wired. */
    get: {
      responses: {
        /** OK */
        200: {
          schema: definitions["response.Envelope"];
        };
        /** Internal Server Error */
        500: {
          schema: definitions["response.Envelope"];
        };
      };
    };
  };
  "/trips": {
    get: {
      responses: {
        /** OK */
        200: {
          schema: definitions["response.Envelope"];
        };
      };
    };
    post: {
      parameters: {
        body: {
          /** Trip */
          body: definitions["triprequest.Create"];
        };
      };
      responses: {
        /** Created */
        201: {
          schema: definitions["response.Envelope"] & {
            data?: definitions["tripresponse.Trip"];
          };
        };
        /** Bad Request */
        400: {
          schema: definitions["response.Envelope"];
        };
      };
    };
  };
  "/trips/{code}": {
    get: {
      responses: {
        /** OK */
        200: {
          schema: definitions["response.Envelope"] & {
            data?: definitions["tripresponse.Trip"];
          };
        };
        /** Forbidden */
        403: {
          schema: definitions["response.Envelope"];
        };
      };
    };
    patch: {
      parameters: {
        body: {
          /** Trip settings */
          body: definitions["triprequest.Update"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["response.Envelope"] & {
            data?: definitions["tripresponse.Trip"];
          };
        };
        /** Bad Request */
        400: {
          schema: definitions["response.Envelope"];
        };
        /** Conflict */
        409: {
          schema: definitions["response.Envelope"];
        };
      };
    };
  };
  "/trips/{code}/balances": {
    get: {
      parameters: {
        path: {
          /** Trip code */
          code: string;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["response.Envelope"] & {
            data?: definitions["balanceresponse.Result"];
          };
        };
        /** Unauthorized */
        401: {
          schema: definitions["response.Envelope"];
        };
        /** Forbidden */
        403: {
          schema: definitions["response.Envelope"];
        };
        /** Not Found */
        404: {
          schema: definitions["response.Envelope"];
        };
        /** Unprocessable Entity */
        422: {
          schema: definitions["response.Envelope"];
        };
      };
    };
  };
  "/trips/{code}/exchange-rates": {
    get: {
      parameters: {
        path: {
          /** Trip code */
          code: string;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["response.Envelope"] & {
            data?: definitions["fxresponse.Rate"][];
          };
        };
        /** Unauthorized */
        401: {
          schema: definitions["response.Envelope"];
        };
        /** Forbidden */
        403: {
          schema: definitions["response.Envelope"];
        };
        /** Not Found */
        404: {
          schema: definitions["response.Envelope"];
        };
      };
    };
    put: {
      parameters: {
        path: {
          /** Trip code */
          code: string;
        };
        body: {
          /** Rate */
          body: definitions["fxrequest.SetRate"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["response.Envelope"] & {
            data?: definitions["fxresponse.Rate"];
          };
        };
        /** Bad Request */
        400: {
          schema: definitions["response.Envelope"];
        };
        /** Unauthorized */
        401: {
          schema: definitions["response.Envelope"];
        };
        /** Forbidden */
        403: {
          schema: definitions["response.Envelope"];
        };
        /** Not Found */
        404: {
          schema: definitions["response.Envelope"];
        };
        /** Unprocessable Entity */
        422: {
          schema: definitions["response.Envelope"];
        };
      };
    };
  };
  "/trips/{code}/expenses": {
    get: {
      parameters: {
        path: {
          /** Trip code */
          code: string;
        };
        query: {
          /** pending, approved, or rejected */
          status?: string;
          /** ISO currency */
          currency?: string;
          /** Payer user ID */
          payer_user_id?: string;
          /** Split participant user ID */
          split_user_id?: string;
          /** Start date (YYYY-MM-DD) */
          date_from?: string;
          /** End date (YYYY-MM-DD) */
          date_to?: string;
          /** Description search */
          q?: string;
          /** date_desc, amount_desc, or created_desc */
          sort?: string;
          /** Page */
          page?: number;
          /** Items per page */
          per_page?: number;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["response.Envelope"] & {
            data?: definitions["expenseresponse.Expense"][];
          };
        };
        /** Forbidden */
        403: {
          schema: definitions["response.Envelope"];
        };
      };
    };
    post: {
      parameters: {
        path: {
          /** Trip code */
          code: string;
        };
        body: {
          /** Expense */
          body: definitions["expenserequest.Create"];
        };
      };
      responses: {
        /** Created */
        201: {
          schema: definitions["response.Envelope"] & {
            data?: definitions["expenseresponse.Expense"];
          };
        };
        /** Bad Request */
        400: {
          schema: definitions["response.Envelope"];
        };
        /** Forbidden */
        403: {
          schema: definitions["response.Envelope"];
        };
      };
    };
  };
  "/trips/{code}/expenses/{id}": {
    get: {
      parameters: {
        path: {
          /** Trip code */
          code: string;
          /** Expense ID */
          id: string;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["response.Envelope"] & {
            data?: definitions["expenseresponse.Expense"];
          };
        };
        /** Not Found */
        404: {
          schema: definitions["response.Envelope"];
        };
      };
    };
    delete: {
      parameters: {
        path: {
          /** Trip code */
          code: string;
          /** Expense ID */
          id: string;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["response.Envelope"];
        };
        /** Forbidden */
        403: {
          schema: definitions["response.Envelope"];
        };
      };
    };
    patch: {
      parameters: {
        path: {
          /** Trip code */
          code: string;
          /** Expense ID */
          id: string;
        };
        body: {
          /** Expense changes */
          body: definitions["expenserequest.Update"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["response.Envelope"] & {
            data?: definitions["expenseresponse.Expense"];
          };
        };
        /** Bad Request */
        400: {
          schema: definitions["response.Envelope"];
        };
        /** Forbidden */
        403: {
          schema: definitions["response.Envelope"];
        };
      };
    };
  };
  "/trips/{code}/expenses/{id}/approve": {
    post: {
      parameters: {
        path: {
          /** Trip code */
          code: string;
          /** Expense ID */
          id: string;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["response.Envelope"] & {
            data?: definitions["expenseresponse.Expense"];
          };
        };
        /** Forbidden */
        403: {
          schema: definitions["response.Envelope"];
        };
      };
    };
  };
  "/trips/{code}/expenses/{id}/reject": {
    post: {
      parameters: {
        path: {
          /** Trip code */
          code: string;
          /** Expense ID */
          id: string;
        };
        body: {
          /** Rejection reason */
          body: definitions["expenserequest.Reject"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["response.Envelope"] & {
            data?: definitions["expenseresponse.Expense"];
          };
        };
        /** Bad Request */
        400: {
          schema: definitions["response.Envelope"];
        };
        /** Forbidden */
        403: {
          schema: definitions["response.Envelope"];
        };
      };
    };
  };
  "/trips/{code}/final-settlement": {
    get: {
      parameters: {
        path: {
          /** Trip code */
          code: string;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["response.Envelope"] & {
            data?: definitions["balanceresponse.FinalPlan"];
          };
        };
        /** Unauthorized */
        401: {
          schema: definitions["response.Envelope"];
        };
        /** Forbidden */
        403: {
          schema: definitions["response.Envelope"];
        };
        /** Not Found */
        404: {
          schema: definitions["response.Envelope"];
        };
        /** Unprocessable Entity */
        422: {
          schema: definitions["response.Envelope"];
        };
      };
    };
  };
  "/trips/{code}/finalize": {
    post: {
      parameters: {
        path: {
          /** Trip code */
          code: string;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["response.Envelope"] & {
            data?: definitions["balanceresponse.FinalPlan"];
          };
        };
        /** Unauthorized */
        401: {
          schema: definitions["response.Envelope"];
        };
        /** Forbidden */
        403: {
          schema: definitions["response.Envelope"];
        };
        /** Not Found */
        404: {
          schema: definitions["response.Envelope"];
        };
        /** Unprocessable Entity */
        422: {
          schema: definitions["response.Envelope"];
        };
      };
    };
  };
  "/trips/{code}/invitations": {
    get: {
      responses: {
        /** OK */
        200: {
          schema: definitions["response.Envelope"];
        };
        /** Forbidden */
        403: {
          schema: definitions["response.Envelope"];
        };
      };
    };
    post: {
      parameters: {
        body: {
          /** Invitation */
          body: definitions["invitationrequest.Create"];
        };
      };
      responses: {
        /** Created */
        201: {
          schema: definitions["response.Envelope"] & {
            data?: definitions["invitationresponse.InviteResult"];
          };
        };
        /** Forbidden */
        403: {
          schema: definitions["response.Envelope"];
        };
      };
    };
  };
  "/trips/{code}/invitations/{id}": {
    delete: {
      responses: {
        /** OK */
        200: {
          schema: definitions["response.Envelope"];
        };
        /** Not Found */
        404: {
          schema: definitions["response.Envelope"];
        };
      };
    };
  };
  "/trips/{code}/join": {
    post: {
      responses: {
        /** Created */
        201: {
          schema: definitions["response.Envelope"] & {
            data?: definitions["participantresponse.Participant"];
          };
        };
        /** Conflict */
        409: {
          schema: definitions["response.Envelope"];
        };
      };
    };
  };
  "/trips/{code}/participants": {
    get: {
      responses: {
        /** OK */
        200: {
          schema: definitions["response.Envelope"];
        };
        /** Forbidden */
        403: {
          schema: definitions["response.Envelope"];
        };
      };
    };
    post: {
      parameters: {
        body: {
          /** Participant */
          body: definitions["participantrequest.Add"];
        };
      };
      responses: {
        /** Created */
        201: {
          schema: definitions["response.Envelope"] & {
            data?: definitions["participantresponse.Participant"];
          };
        };
        /** Forbidden */
        403: {
          schema: definitions["response.Envelope"];
        };
      };
    };
  };
  "/trips/{code}/participants/{id}": {
    delete: {
      responses: {
        /** OK */
        200: {
          schema: definitions["response.Envelope"];
        };
        /** Forbidden */
        403: {
          schema: definitions["response.Envelope"];
        };
      };
    };
    patch: {
      parameters: {
        body: {
          /** Participant details */
          body: definitions["participantrequest.Update"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["response.Envelope"] & {
            data?: definitions["participantresponse.Participant"];
          };
        };
        /** Forbidden */
        403: {
          schema: definitions["response.Envelope"];
        };
      };
    };
  };
  "/trips/{code}/receipts": {
    get: {
      parameters: {
        path: {
          /** Trip code */
          code: string;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["response.Envelope"] & {
            data?: definitions["receipt.receiptResponse"][];
          };
        };
      };
    };
    post: {
      parameters: {
        path: {
          /** Trip code */
          code: string;
        };
        formData: {
          /** JPEG, PNG, or WebP receipt (max 10 MB) */
          file: unknown;
        };
      };
      responses: {
        /** Created */
        201: {
          schema: definitions["response.Envelope"] & {
            data?: definitions["receipt.receiptResponse"];
          };
        };
      };
    };
  };
  "/trips/{code}/receipts/{id}": {
    get: {
      parameters: {
        path: {
          /** Trip code */
          code: string;
          /** Receipt ID */
          id: string;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["response.Envelope"] & {
            data?: definitions["receipt.receiptResponse"];
          };
        };
      };
    };
    delete: {
      parameters: {
        path: {
          /** Trip code */
          code: string;
          /** Receipt ID */
          id: string;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["response.Envelope"];
        };
      };
    };
  };
  "/trips/{code}/receipts/{id}/assignments": {
    put: {
      parameters: {
        path: {
          /** Trip code */
          code: string;
          /** Receipt ID */
          id: string;
        };
        body: {
          /** Assignments */
          body: definitions["receipt.assignmentRequest"][];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["response.Envelope"];
        };
      };
    };
  };
  "/trips/{code}/receipts/{id}/convert": {
    post: {
      parameters: {
        path: {
          /** Trip code */
          code: string;
          /** Receipt ID */
          id: string;
        };
        body: {
          /** Expense details and payers */
          body: definitions["receipt.convertRequest"];
        };
      };
      responses: {
        /** Created */
        201: {
          schema: definitions["response.Envelope"] & {
            data?: definitions["expenseresponse.Expense"];
          };
        };
      };
    };
  };
  "/trips/{code}/receipts/{id}/extract": {
    post: {
      parameters: {
        path: {
          /** Trip code */
          code: string;
          /** Receipt ID */
          id: string;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["response.Envelope"] & {
            data?: definitions["receipt.receiptResponse"];
          };
        };
      };
    };
  };
  "/trips/{code}/receipts/{id}/items": {
    post: {
      parameters: {
        path: {
          /** Trip code */
          code: string;
          /** Receipt ID */
          id: string;
        };
        body: {
          /** Line item */
          body: definitions["receipt.itemRequest"];
        };
      };
      responses: {
        /** Created */
        201: {
          schema: definitions["response.Envelope"] & {
            data?: definitions["receipt.itemResponse"];
          };
        };
      };
    };
  };
  "/trips/{code}/receipts/{id}/items/{itemId}": {
    delete: {
      parameters: {
        path: {
          /** Trip code */
          code: string;
          /** Receipt ID */
          id: string;
          /** Item ID */
          itemId: string;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["response.Envelope"];
        };
      };
    };
    patch: {
      parameters: {
        path: {
          /** Trip code */
          code: string;
          /** Receipt ID */
          id: string;
          /** Item ID */
          itemId: string;
        };
        body: {
          /** Line item changes */
          body: definitions["receipt.itemRequest"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["response.Envelope"] & {
            data?: definitions["receipt.itemResponse"];
          };
        };
      };
    };
  };
  "/trips/{code}/receipts/{id}/shares": {
    get: {
      parameters: {
        path: {
          /** Trip code */
          code: string;
          /** Receipt ID */
          id: string;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["response.Envelope"] & {
            data?: definitions["receipt.shareResponse"];
          };
        };
      };
    };
  };
  "/trips/{code}/settlements": {
    get: {
      parameters: {
        path: {
          /** Trip code */
          code: string;
        };
        query: {
          /** Page number */
          page?: number;
          /** Rows per page */
          per_page?: number;
          /** Filter by status */
          status?: "pending" | "approved" | "rejected";
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["response.Envelope"] & {
            data?: definitions["settlementresponse.Settlement"][];
          };
        };
        /** Unauthorized */
        401: {
          schema: definitions["response.Envelope"];
        };
        /** Forbidden */
        403: {
          schema: definitions["response.Envelope"];
        };
        /** Not Found */
        404: {
          schema: definitions["response.Envelope"];
        };
      };
    };
    post: {
      parameters: {
        path: {
          /** Trip code */
          code: string;
        };
        body: {
          /** Settlement */
          body: definitions["settlementrequest.Create"];
        };
      };
      responses: {
        /** Created */
        201: {
          schema: definitions["response.Envelope"] & {
            data?: definitions["settlementresponse.Settlement"];
          };
        };
        /** Bad Request */
        400: {
          schema: definitions["response.Envelope"];
        };
        /** Unauthorized */
        401: {
          schema: definitions["response.Envelope"];
        };
        /** Forbidden */
        403: {
          schema: definitions["response.Envelope"];
        };
        /** Not Found */
        404: {
          schema: definitions["response.Envelope"];
        };
        /** Unprocessable Entity */
        422: {
          schema: definitions["response.Envelope"];
        };
      };
    };
  };
  "/trips/{code}/settlements/{id}": {
    delete: {
      parameters: {
        path: {
          /** Trip code */
          code: string;
          /** Settlement ID */
          id: string;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["response.Envelope"];
        };
        /** Unauthorized */
        401: {
          schema: definitions["response.Envelope"];
        };
        /** Forbidden */
        403: {
          schema: definitions["response.Envelope"];
        };
        /** Not Found */
        404: {
          schema: definitions["response.Envelope"];
        };
        /** Unprocessable Entity */
        422: {
          schema: definitions["response.Envelope"];
        };
      };
    };
  };
  "/trips/{code}/settlements/{id}/approve": {
    post: {
      parameters: {
        path: {
          /** Trip code */
          code: string;
          /** Settlement ID */
          id: string;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["response.Envelope"] & {
            data?: definitions["settlementresponse.Settlement"];
          };
        };
        /** Unauthorized */
        401: {
          schema: definitions["response.Envelope"];
        };
        /** Forbidden */
        403: {
          schema: definitions["response.Envelope"];
        };
        /** Not Found */
        404: {
          schema: definitions["response.Envelope"];
        };
        /** Unprocessable Entity */
        422: {
          schema: definitions["response.Envelope"];
        };
      };
    };
  };
  "/trips/{code}/settlements/{id}/reject": {
    post: {
      parameters: {
        path: {
          /** Trip code */
          code: string;
          /** Settlement ID */
          id: string;
        };
        body: {
          /** Rejection reason */
          body: definitions["settlementrequest.Reject"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["response.Envelope"] & {
            data?: definitions["settlementresponse.Settlement"];
          };
        };
        /** Bad Request */
        400: {
          schema: definitions["response.Envelope"];
        };
        /** Unauthorized */
        401: {
          schema: definitions["response.Envelope"];
        };
        /** Forbidden */
        403: {
          schema: definitions["response.Envelope"];
        };
        /** Not Found */
        404: {
          schema: definitions["response.Envelope"];
        };
        /** Unprocessable Entity */
        422: {
          schema: definitions["response.Envelope"];
        };
      };
    };
  };
  "/trips/{code}/unfinalize": {
    post: {
      parameters: {
        path: {
          /** Trip code */
          code: string;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["response.Envelope"];
        };
        /** Unauthorized */
        401: {
          schema: definitions["response.Envelope"];
        };
        /** Forbidden */
        403: {
          schema: definitions["response.Envelope"];
        };
        /** Not Found */
        404: {
          schema: definitions["response.Envelope"];
        };
        /** Unprocessable Entity */
        422: {
          schema: definitions["response.Envelope"];
        };
      };
    };
  };
  "/users/lookup": {
    get: {
      parameters: {
        query: {
          /** Exact email address */
          email: string;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["response.Envelope"] & {
            data?: definitions["userresponse.Lookup"];
          };
        };
        /** Bad Request */
        400: {
          schema: definitions["response.Envelope"];
        };
        /** Not Found */
        404: {
          schema: definitions["response.Envelope"];
        };
      };
    };
  };
  "/users/me": {
    get: {
      responses: {
        /** OK */
        200: {
          schema: definitions["response.Envelope"] & {
            data?: definitions["userresponse.User"];
          };
        };
        /** Unauthorized */
        401: {
          schema: definitions["response.Envelope"];
        };
      };
    };
    patch: {
      parameters: {
        body: {
          /** Profile changes */
          body: definitions["userrequest.Update"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["response.Envelope"] & {
            data?: definitions["userresponse.User"];
          };
        };
        /** Bad Request */
        400: {
          schema: definitions["response.Envelope"];
        };
        /** Unauthorized */
        401: {
          schema: definitions["response.Envelope"];
        };
      };
    };
  };
}

export interface definitions {
  "authrequest.Login": {
    email: string;
    password: string;
  };
  "authrequest.Refresh": {
    refresh_token: string;
  };
  "authrequest.Register": {
    email: string;
    name: string;
    password: string;
  };
  "authresponse.Session": {
    access_token?: string;
    access_token_expires_at?: string;
    pending_invitations?: definitions["invitationresponse.Invitation"][];
    refresh_token?: string;
    refresh_token_expires_at?: string;
    user?: definitions["userresponse.User"];
  };
  "balanceresponse.AppliedRate": {
    from?: string;
    is_final?: boolean;
    rate?: string;
    to?: string;
  };
  "balanceresponse.FinalPlan": {
    base_currency?: string;
    transfers?: definitions["balanceresponse.Transfer"][];
  };
  "balanceresponse.ParticipantBalance": {
    net_balance?: string;
    total_owed?: string;
    total_paid?: string;
    user?: definitions["balanceresponse.User"];
    user_id?: string;
  };
  "balanceresponse.Result": {
    balances?: definitions["balanceresponse.ParticipantBalance"][];
    base_currency?: string;
    debts?: definitions["balanceresponse.Transfer"][];
    rates_used?: definitions["balanceresponse.AppliedRate"][];
    summary?: definitions["balanceresponse.Summary"];
  };
  "balanceresponse.Summary": {
    expense_count?: number;
    pending_expense_count?: number;
    pending_settlement_count?: number;
    settlement_count?: number;
    total_expenses?: string;
    total_settled?: string;
    unsettled_total?: string;
  };
  "balanceresponse.Transfer": {
    amount?: string;
    bank_account_holder?: string;
    bank_account_number?: string;
    /**
     * @description Bank details are present only for viewers allowed to see them — the payer of this transfer
     * or the planner. They are nil for everyone else.
     */
    bank_name?: string;
    currency?: string;
    from_user_id?: string;
    to_user_id?: string;
  };
  "balanceresponse.User": {
    avatar_url?: string;
    created_at?: string;
    email?: string;
    id?: string;
    name?: string;
    updated_at?: string;
  };
  "expenserequest.Create": {
    amount: string;
    currency: string;
    description: string;
    expense_date: string;
    note?: string;
    participants?: string[];
    payers: definitions["expenserequest.Payer"][];
    /** @enum {string} */
    split_type: "equal" | "manual" | "item";
    splits?: definitions["expenserequest.Split"][];
  };
  "expenserequest.Payer": {
    amount: string;
    user_id: string;
  };
  "expenserequest.Reject": {
    reason: string;
  };
  "expenserequest.Split": {
    amount: string;
    user_id: string;
  };
  "expenserequest.Update": {
    amount?: string;
    currency?: string;
    description?: string;
    expense_date?: string;
    note?: string;
    participants?: string[];
    payers?: definitions["expenserequest.Payer"][];
    split_type?: string;
    splits?: definitions["expenserequest.Split"][];
    version: number;
  };
  "expenseresponse.Expense": {
    amount?: string;
    approved_at?: string;
    approved_by?: definitions["expenseresponse.User"];
    can_approve?: boolean;
    can_delete?: boolean;
    can_edit?: boolean;
    can_reject?: boolean;
    created_at?: string;
    created_by?: definitions["expenseresponse.User"];
    currency?: string;
    description?: string;
    expense_date?: string;
    id?: string;
    note?: string;
    payers?: definitions["expenseresponse.Payer"][];
    rejected_reason?: string;
    source?: string;
    split_type?: string;
    splits?: definitions["expenseresponse.Split"][];
    status?: string;
    trip_id?: string;
    updated_at?: string;
    version?: number;
  };
  "expenseresponse.Payer": {
    amount?: string;
    user?: definitions["expenseresponse.User"];
    user_id?: string;
  };
  "expenseresponse.Split": {
    amount?: string;
    user?: definitions["expenseresponse.User"];
    user_id?: string;
  };
  "expenseresponse.User": {
    avatar_url?: string;
    created_at?: string;
    email?: string;
    id?: string;
    name?: string;
    updated_at?: string;
  };
  "fxrequest.SetRate": {
    from: string;
    rate: string;
    to: string;
  };
  "fxresponse.Rate": {
    from?: string;
    id?: string;
    /** @description IsFinal marks a rate locked at finalization; locked rates survive an unfinalize. */
    is_final?: boolean;
    rate?: string;
    source?: string;
    to?: string;
    trip_id?: string;
  };
  "invitationrequest.Create": {
    email: string;
  };
  "invitationresponse.Invitation": {
    email?: string;
    expires_at?: string;
    id?: string;
    status?: string;
    token?: string;
    trip_id?: string;
  };
  "invitationresponse.InviteResult": {
    invitation?: definitions["invitationresponse.Invitation"];
    invite_link?: string;
    participant?: definitions["participantresponse.Participant"];
    status?: string;
  };
  "participantrequest.Add": {
    user_id: string;
  };
  "participantrequest.BankInfo": {
    account_holder: string;
    account_number: string;
    bank_name: string;
  };
  "participantrequest.Update": {
    bank_info?: definitions["participantrequest.BankInfo"];
    /** @enum {string} */
    role?: "planner" | "participant";
  };
  "participantresponse.BankInfo": {
    account_holder?: string;
    account_number?: string;
    bank_name?: string;
  };
  "participantresponse.Participant": {
    bank_info?: definitions["participantresponse.BankInfo"];
    id?: string;
    joined_at?: string;
    role?: string;
    trip_id?: string;
    user?: definitions["participantresponse.User"];
    user_id?: string;
  };
  "participantresponse.User": {
    avatar_url?: string;
    email?: string;
    id?: string;
    name?: string;
  };
  "receipt.assignmentRequest": {
    item_id?: string;
    user_ids?: string[];
  };
  "receipt.convertRequest": {
    description?: string;
    expense_date?: string;
    payers?: {
      amount?: string;
      user_id?: string;
    }[];
  };
  "receipt.itemRequest": {
    name?: string;
    quantity?: string;
    total_price?: string;
    unit_price?: string;
  };
  "receipt.itemResponse": {
    assignee_ids?: string[];
    id?: string;
    name?: string;
    quantity?: string;
    receipt_id?: string;
    sort_order?: number;
    total_price?: string;
    unit_price?: string;
  };
  "receipt.receiptResponse": {
    content_type?: string;
    created_at?: string;
    currency?: string;
    discrepancy?: boolean;
    expense_id?: string;
    failure_reason?: string;
    id?: string;
    image_url?: string;
    items?: definitions["receipt.itemResponse"][];
    merchant?: string;
    provider?: string;
    provider_model?: string;
    receipt_date?: string;
    service_charge?: string;
    size_bytes?: number;
    status?: string;
    subtotal?: string;
    tax?: string;
    total?: string;
    trip_id?: string;
    updated_at?: string;
    uploaded_by?: string;
    uploader?: definitions["userresponse.User"];
  };
  "receipt.shareResponse": {
    currency?: string;
    discrepancy?: boolean;
    items_total?: string;
    per_user?: definitions["receipt.userShareResponse"][];
    service_charge?: string;
    tax?: string;
    total?: string;
    unassigned_items?: string[];
  };
  "receipt.userShareResponse": {
    items_subtotal?: string;
    service_charge?: string;
    tax?: string;
    total?: string;
    user_id?: string;
  };
  "response.Envelope": {
    code?: string;
    data?: unknown;
    errors?: definitions["response.FieldError"][];
    message?: string;
    meta?: unknown;
    success?: boolean;
    /** @example 2026-08-05T09:12:33.412Z */
    timestamp?: string;
    trace_id?: string;
  };
  "response.FieldError": {
    field?: string;
    message?: string;
    rule?: string;
  };
  "settlementrequest.Create": {
    amount: string;
    currency: string;
    from_user_id: string;
    /** @enum {string} */
    method: "cash" | "bank_transfer";
    note?: string;
    proof_url?: string;
    to_user_id: string;
  };
  "settlementrequest.Reject": {
    reason: string;
  };
  "settlementresponse.Settlement": {
    amount?: string;
    approved_at?: string;
    approved_by_user_id?: string;
    bank_account_holder?: string;
    bank_account_number?: string;
    /**
     * @description Bank details are the snapshot taken when the settlement was recorded, not a live read of the
     * payee's participant record. The account number is always masked on the way out.
     */
    bank_name?: string;
    created_at?: string;
    currency?: string;
    from_user?: definitions["settlementresponse.User"];
    from_user_id?: string;
    id?: string;
    method?: string;
    note?: string;
    proof_url?: string;
    rejected_reason?: string;
    status?: string;
    to_user?: definitions["settlementresponse.User"];
    to_user_id?: string;
    trip_id?: string;
    updated_at?: string;
    version?: number;
  };
  "settlementresponse.User": {
    avatar_url?: string;
    created_at?: string;
    email?: string;
    id?: string;
    name?: string;
    updated_at?: string;
  };
  "triprequest.Create": {
    allow_settlement_before_end?: boolean;
    approval_required_expenses?: boolean;
    approval_required_settlements?: boolean;
    base_currency: string;
    /** @enum {string} */
    edit_permission: "everyone" | "own_only";
    end_date: string;
    multi_currency_enabled?: boolean;
    name: string;
    start_date: string;
  };
  "triprequest.Update": {
    allow_settlement_before_end?: boolean;
    approval_required_expenses?: boolean;
    approval_required_settlements?: boolean;
    base_currency: string;
    /** @enum {string} */
    edit_permission: "everyone" | "own_only";
    multi_currency_enabled?: boolean;
    name: string;
    version: number;
  };
  "tripresponse.Settings": {
    allow_settlement_before_end?: boolean;
    approval_required_expenses?: boolean;
    approval_required_settlements?: boolean;
    edit_permission?: string;
    multi_currency_enabled?: boolean;
  };
  "tripresponse.Trip": {
    base_currency?: string;
    can_edit_settings?: boolean;
    code?: string;
    end_date?: string;
    id?: string;
    is_finalized?: boolean;
    name?: string;
    planner_id?: string;
    settings?: definitions["tripresponse.Settings"];
    start_date?: string;
    version?: number;
  };
  "userrequest.Update": {
    avatar_url?: string;
    name?: string;
  };
  "userresponse.Lookup": {
    email?: string;
    id?: string;
    name?: string;
  };
  "userresponse.User": {
    avatar_url?: string;
    created_at?: string;
    email?: string;
    id?: string;
    name?: string;
    updated_at?: string;
  };
}

export interface operations {}

export interface external {}
